version: '3.1'
services:

  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    container_name: db
    networks: 
      - db
      
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    image: node:16
    networks:
      - node
    ports:
      - "3000:3000"
    container_name: node
    command: bash -c 'npm install && npm run build && npm start'
    depends_on:
      - db
      
networks:
  db:
    driver: bridge
  node:
    driver: bridge